# https://www.home-assistant.io/integrations/default_config/
default_config:

lovelace:
  resource_mode: yaml
  dashboards:
    lovelace:
      mode: yaml
      filename: ui-lovelace.yaml
      title: iAlarm Test
      icon: mdi:shield-home
      show_in_sidebar: true

script:
  test_disarm:
    alias: "Test Disarm (1234)"
    sequence:
      - service: alarm_control_panel.alarm_disarm
        target:
          entity_id: alarm_control_panel.ialarm_panel_ialarm_panel
        data:
          code: "1234"
  test_arm:
    alias: "Test Arm Away (1234)"
    sequence:
      - service: alarm_control_panel.alarm_arm_away
        target:
          entity_id: alarm_control_panel.ialarm_panel_ialarm_panel
        data:
          code: "1234"

logger:
  default: info
  logs:
    custom_components.ialarm_controller: debug
    custom_components.ialarm_controller.sensor: debug
    homeassistant.core: info
    homeassistant.components.websocket_api: info
    homeassistant.helpers.script.websocket_api_script: info
    homeassistant.components.websocket_api.http.connection: info
